In [1]:
import numpy as np
 
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])

# define y for output dataset            
y = np.array([[0,0,1,1]]).T

In [2]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,3)) - 1

# define syn1
syn1 = 2*np.random.random((3,3)) - 1

iter = 0

In [3]:
for iter in range(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
 
    # how much did we miss?
    l1_error = y - l1
    l2_error = y - l2
 
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    l2_delta = l2_error * nonlin(l2,True)
    
    # update weights
    syn0 += np.dot(l0.T,l1_delta)
    # syn1 update weights
    syn1 += np.dot(l1.T,l2_delta)
    
print("Output After Training:")
print(l1)
print("\n\n")
print(l2)

Output After Training:
[[0.00966835 0.00966881 0.00967224]
 [0.00786365 0.0078617  0.00786433]
 [0.99359085 0.99359281 0.99359069]
 [0.9921173  0.99211737 0.99211461]]



[[0.50813907 0.50813856 0.50813891]
 [0.5066189  0.50661825 0.506619  ]
 [0.96596356 0.96596359 0.96596355]
 [0.96579992 0.96579993 0.96579993]]
